TENSORBOARD_DIR: "/checkpoint/eundersander/gala_kinematic/tb/gala_kinematic_ddppo"
CHECKPOINT_FOLDER: "/checkpoint/eundersander/gala_kinematic/ckpt/gala_kinematic_ddppo"
VIDEO_DIR: "../videos"
VIDEO_OPTION: ["disk"]
REWARD_SCALE: 1.0 # 0.01
NUM_CHECKPOINTS: 10
BATCHED_ENV: True
OVERLAP_PHYSICS: True
SAVE_VIDEOS_INTERVAL: 500
LOG_INTERVAL: 1
NUM_UPDATES: -1
TOTAL_NUM_STEPS: 50000000.0
NUM_ENVIRONMENTS: 2
MAX_EPISODE_LENGTH: 500
STAGGER: False
TEST_EPISODE_COUNT: 10
ENABLE_ROBOT_COLLISION: True
ENABLE_HELD_OBJECT_COLLISION: True
PICK_REWARD : 5.0
TASK_IS_PLACE : False
NPNP_SUCCESS_REWARD: 10.0
NPNP_SUCCESS_THRESH: 0.3 #0.05
NPNP_FAILURE_PENALTY: 10.0
STATE_SENSORS:
  ROBOT_START_RELATIVE:
    TYPE: "RobotStartSensorConfig"
    polar: True
    obs_key: "robot_start_relative"
    shape: 3
  ROBOT_TARGET_RELATIVE:
    TYPE: "RobotTargetSensorConfig"
    polar: True
    obs_key: "robot_target_relative"
    shape: 3
  ROBOT_GOAL_RELATIVE:
    TYPE: "RobotGoalSensorConfig"
    polar: True
    obs_key: "robot_goal_relative"
    shape: 3
  EE_GOAL_RELATIVE:
    TYPE: "EEGoalSensorConfig"
    polar: True
    obs_key: "ee_goal_relative"
    shape: 3
  EE_START_RELATIVE:
    TYPE: "EEStartSensorConfig"
    polar: True
    obs_key: "ee_start_relative"
    shape: 3
  EE_TARGET_RELATIVE:
    TYPE: "EETargetSensorConfig"
    polar: True
    obs_key: "ee_target_relative"
    shape: 3
  ROBOT_EE_RELATIVE:
    TYPE: "RobotEESensorConfig"
    polar: True
    obs_key: "robot_ee_relative"
    shape: 3
  JOINT_SENSOR:
    TYPE: "JointSensorConfig"
    obs_key: "joint_pos"
    shape: 7
  STEP_COUNT_SENSOR:
    TYPE: "StepCountSensorConfig"
    obs_key: "step_count"
    shape: 3
  IS_HOLDING_SENSOR:
    TYPE: "JointSensorConfig"
    obs_key: "is_holding"
    shape: 1
VIDEO_RENDER_ALL_INFO: True
SENSORS: ["DEPTH_SENSOR", "RGB_SENSOR", "ROBOT_START_RELATIVE", "ROBOT_TARGET_RELATIVE", "EE_START_RELATIVE", "EE_TARGET_RELATIVE", "ROBOT_EE_RELATIVE", "ROBOT_GOAL_RELATIVE", "EE_GOAL_RELATIVE", "IS_HOLDING_SENSOR", "JOINT_SENSOR", "STEP_COUNT_SENSOR", "DEBUG_RGB_SENSOR"]
SIMULATOR:
  AGENTS: ['AGENT_0']
  AGENT_0:
    SENSORS: ['HEAD_RGB_SENSOR']
  HEAD_RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
WRITER_TYPE: "wb"
WB:
  PROJECT_NAME: "gala"
  ENTITY: "vincentpierre"
  GROUP: ""
  RUN_NAME: ""
RL:
  PPO:
    ppo_epoch: 1
    num_mini_batch: 2
    num_steps: 32
    entropy_coef: 0.0001
    lr: 2.5e-4
    use_normalized_advantage: True
    use_linear_lr_decay: False
    # max_grad_norm: 1.0e+32
  POLICY:
    name: "PointNavBaselinePolicy"
    action_distribution_type: "gaussian"
  DDPPO:
    backbone: "PointNavResNetPolicy"
FORCE_BLIND_POLICY: False
