base_task_config_path: "habitat-lab/habitat/config/tasks/eqa_mp3d.yaml"
trainer_name: "eqa-cnn-pretrain"

simulator_gpu_id: 0
torch_gpu_id: 0

dataset_PATH: "data/datasets/eqa/eqa_cnn_pretrain/{split}/{split}.db"

eval_ckpt_path_dir: "data/eqa/eqa_cnn_pretrain/checkpoints/epoch_5.ckpt"

checkpoint_folder: "data/eqa/eqa_cnn_pretrain/checkpoints"
tensorboard_dir: "data/eqa/eqa_cnn_pretrain/tb"
RESULTS_DIR: "data/eqa/eqa_cnn_pretrain/results/{split}/{type}"
OUTPUT_LOG_DIR: data/eqa/eqa_cnn_pretrain/logs

LOG_METRICS: True
log_interval: 50
eval_save_results: True
eval_save_results_interval: 50
# Force PyTorch to be single threaded as
# this improves performance considerably
force_torch_single_threaded: True

IL:
  EQACNNPretrain:
    # params
    max_epochs: 5
    batch_size: 20
    lr: 1e-3
