base_task_config_path: habitat-lab/habitat/config/tasks/rearrange/pick.yaml

SENSE_PLAN_ACT:
  verbose: True
  RUN_FREQ: 2
  KINEMATIC_CTrl: True
  N_GRASPS: 100
  MP_OBJ: True
  MP_MARGIN: null
  MP_RENDER: True
  TIMEOUT: 3
  EXEC_EE_THRESH: 0.1
  # "Priv" or "Reg"
  mp_sim_type: "Priv"
  video_dir: 'data/vids'
  debug_dir: "data/mp_test"
  count_obj_collisions: True
  grasp_gen_is_verbose: True
  ik_dist_thresh: 0.1

habitat:
  success_reward: 2000.0
  end_on_success: False
  gym:
    obs_keys: ['joint', 'ee_pos']
    desired_goal_keys: ['obj_goal_pos_sensor']
    achieved_goal_keys: []
    action_keys: ['arm_action']

rl:
    # If true, does not care about navigability or collisions with objects when spawning
    # robot
    easy_init: False
video_dir: "data/vids/"
video_optionS: ["disk"]

count_obj_collisions: True
