objects:
  - name: hab2|0
    expr_type: rigid_obj_type
  - name: ROBOT_0
    expr_type: robot_type

stage_goals: {}
init: []

goal:
  expr_type: AND
  sub_exprs:
    - holding(hab2|0, ROBOT_0)

solution:
  - nav(hab2|0,ROBOT_0)
  - pick(hab2|0,ROBOT_0)
